//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISFORM_WEB.ServicioWcf {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioWcf.IServicio")]
    public interface IServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AutenticarUsuario", ReplyAction="http://tempuri.org/IServicio/AutenticarUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/AutenticarUsuarioErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        Dominio.VistaUsuario AutenticarUsuario(string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AutenticarUsuario", ReplyAction="http://tempuri.org/IServicio/AutenticarUsuarioResponse")]
        System.Threading.Tasks.Task<Dominio.VistaUsuario> AutenticarUsuarioAsync(string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarUbigeo", ReplyAction="http://tempuri.org/IServicio/ListarUbigeoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarUbigeoErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        Dominio.Ubigeo[] ListarUbigeo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarUbigeo", ReplyAction="http://tempuri.org/IServicio/ListarUbigeoResponse")]
        System.Threading.Tasks.Task<Dominio.Ubigeo[]> ListarUbigeoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/TrabajadorOperacion", ReplyAction="http://tempuri.org/IServicio/TrabajadorOperacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/TrabajadorOperacionErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        int TrabajadorOperacion(Dominio.Trabajador oTrabajador, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/TrabajadorOperacion", ReplyAction="http://tempuri.org/IServicio/TrabajadorOperacionResponse")]
        System.Threading.Tasks.Task<int> TrabajadorOperacionAsync(Dominio.Trabajador oTrabajador, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTrabajador", ReplyAction="http://tempuri.org/IServicio/ListarTrabajadorResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarTrabajadorErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        Dominio.Trabajador[] ListarTrabajador();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTrabajador", ReplyAction="http://tempuri.org/IServicio/ListarTrabajadorResponse")]
        System.Threading.Tasks.Task<Dominio.Trabajador[]> ListarTrabajadorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EmpresaOperacion", ReplyAction="http://tempuri.org/IServicio/EmpresaOperacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/EmpresaOperacionErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        int EmpresaOperacion(Dominio.Empresa oEmpresa, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EmpresaOperacion", ReplyAction="http://tempuri.org/IServicio/EmpresaOperacionResponse")]
        System.Threading.Tasks.Task<int> EmpresaOperacionAsync(Dominio.Empresa oEmpresa, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarEmpresa", ReplyAction="http://tempuri.org/IServicio/ListarEmpresaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarEmpresaErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        Dominio.Empresa[] ListarEmpresa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarEmpresa", ReplyAction="http://tempuri.org/IServicio/ListarEmpresaResponse")]
        System.Threading.Tasks.Task<Dominio.Empresa[]> ListarEmpresaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ProgresoEmpresaOperacion", ReplyAction="http://tempuri.org/IServicio/ProgresoEmpresaOperacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ProgresoEmpresaOperacionErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        int ProgresoEmpresaOperacion(Dominio.ProgresoEmpresa oProgresoEmpresa, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ProgresoEmpresaOperacion", ReplyAction="http://tempuri.org/IServicio/ProgresoEmpresaOperacionResponse")]
        System.Threading.Tasks.Task<int> ProgresoEmpresaOperacionAsync(Dominio.ProgresoEmpresa oProgresoEmpresa, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarProgresoEmpresa", ReplyAction="http://tempuri.org/IServicio/ListarProgresoEmpresaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarProgresoEmpresaErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        Dominio.ProgresoEmpresa[] ListarProgresoEmpresa(string idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarProgresoEmpresa", ReplyAction="http://tempuri.org/IServicio/ListarProgresoEmpresaResponse")]
        System.Threading.Tasks.Task<Dominio.ProgresoEmpresa[]> ListarProgresoEmpresaAsync(string idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/Criterio1Operacion", ReplyAction="http://tempuri.org/IServicio/Criterio1OperacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/Criterio1OperacionErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        int Criterio1Operacion(Dominio.Criterio1 oCriterio1, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/Criterio1Operacion", ReplyAction="http://tempuri.org/IServicio/Criterio1OperacionResponse")]
        System.Threading.Tasks.Task<int> Criterio1OperacionAsync(Dominio.Criterio1 oCriterio1, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarCriterio1", ReplyAction="http://tempuri.org/IServicio/ListarCriterio1Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarCriterio1ErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        Dominio.Criterio1[] ListarCriterio1(string idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarCriterio1", ReplyAction="http://tempuri.org/IServicio/ListarCriterio1Response")]
        System.Threading.Tasks.Task<Dominio.Criterio1[]> ListarCriterio1Async(string idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/Criterio2Operacion", ReplyAction="http://tempuri.org/IServicio/Criterio2OperacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/Criterio2OperacionErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        int Criterio2Operacion(Dominio.Criterio2 oCriterio2, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/Criterio2Operacion", ReplyAction="http://tempuri.org/IServicio/Criterio2OperacionResponse")]
        System.Threading.Tasks.Task<int> Criterio2OperacionAsync(Dominio.Criterio2 oCriterio2, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarCriterio2", ReplyAction="http://tempuri.org/IServicio/ListarCriterio2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarCriterio2ErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        Dominio.Criterio2[] ListarCriterio2(string idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarCriterio2", ReplyAction="http://tempuri.org/IServicio/ListarCriterio2Response")]
        System.Threading.Tasks.Task<Dominio.Criterio2[]> ListarCriterio2Async(string idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/Criterio3Operacion", ReplyAction="http://tempuri.org/IServicio/Criterio3OperacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/Criterio3OperacionErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        int Criterio3Operacion(Dominio.Criterio3 oCriterio3, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/Criterio3Operacion", ReplyAction="http://tempuri.org/IServicio/Criterio3OperacionResponse")]
        System.Threading.Tasks.Task<int> Criterio3OperacionAsync(Dominio.Criterio3 oCriterio3, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarCriterio3", ReplyAction="http://tempuri.org/IServicio/ListarCriterio3Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarCriterio3ErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        Dominio.Criterio3[] ListarCriterio3(string idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarCriterio3", ReplyAction="http://tempuri.org/IServicio/ListarCriterio3Response")]
        System.Threading.Tasks.Task<Dominio.Criterio3[]> ListarCriterio3Async(string idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/TrabajadorPuestoOperacion", ReplyAction="http://tempuri.org/IServicio/TrabajadorPuestoOperacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/TrabajadorPuestoOperacionErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        int TrabajadorPuestoOperacion(Dominio.TrabajadorPuesto oTrabajadorPuesto, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/TrabajadorPuestoOperacion", ReplyAction="http://tempuri.org/IServicio/TrabajadorPuestoOperacionResponse")]
        System.Threading.Tasks.Task<int> TrabajadorPuestoOperacionAsync(Dominio.TrabajadorPuesto oTrabajadorPuesto, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/PruebasCovidOperacion", ReplyAction="http://tempuri.org/IServicio/PruebasCovidOperacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/PruebasCovidOperacionErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        int PruebasCovidOperacion(Dominio.PruebasCovid oPruebasCovid, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/PruebasCovidOperacion", ReplyAction="http://tempuri.org/IServicio/PruebasCovidOperacionResponse")]
        System.Threading.Tasks.Task<int> PruebasCovidOperacionAsync(Dominio.PruebasCovid oPruebasCovid, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/PruebasCovidMasivo", ReplyAction="http://tempuri.org/IServicio/PruebasCovidMasivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/PruebasCovidMasivoErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        int PruebasCovidMasivo(string data, string idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/PruebasCovidMasivo", ReplyAction="http://tempuri.org/IServicio/PruebasCovidMasivoResponse")]
        System.Threading.Tasks.Task<int> PruebasCovidMasivoAsync(string data, string idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/PruebasCovidCarga", ReplyAction="http://tempuri.org/IServicio/PruebasCovidCargaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/PruebasCovidCargaErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        int PruebasCovidCarga(Dominio.CargaMasiva[] lstCarga, string idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/PruebasCovidCarga", ReplyAction="http://tempuri.org/IServicio/PruebasCovidCargaResponse")]
        System.Threading.Tasks.Task<int> PruebasCovidCargaAsync(Dominio.CargaMasiva[] lstCarga, string idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CtrlAccionOperacion", ReplyAction="http://tempuri.org/IServicio/CtrlAccionOperacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/CtrlAccionOperacionErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        int CtrlAccionOperacion(Dominio.CtrlAccion oCtrlAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CtrlAccionOperacion", ReplyAction="http://tempuri.org/IServicio/CtrlAccionOperacionResponse")]
        System.Threading.Tasks.Task<int> CtrlAccionOperacionAsync(Dominio.CtrlAccion oCtrlAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/IncidenciaOperacion", ReplyAction="http://tempuri.org/IServicio/IncidenciaOperacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/IncidenciaOperacionErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        int IncidenciaOperacion(Dominio.Incidencia oIncidencia, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/IncidenciaOperacion", ReplyAction="http://tempuri.org/IServicio/IncidenciaOperacionResponse")]
        System.Threading.Tasks.Task<int> IncidenciaOperacionAsync(Dominio.Incidencia oIncidencia, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/IncidenciaImagen", ReplyAction="http://tempuri.org/IServicio/IncidenciaImagenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/IncidenciaImagenErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        int IncidenciaImagen([System.ServiceModel.MessageParameterAttribute(Name="IncidenciaImagen")] Dominio.Imagen IncidenciaImagen1, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/IncidenciaImagen", ReplyAction="http://tempuri.org/IServicio/IncidenciaImagenResponse")]
        System.Threading.Tasks.Task<int> IncidenciaImagenAsync(Dominio.Imagen IncidenciaImagen, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarUbigeoCsv", ReplyAction="http://tempuri.org/IServicio/ListarUbigeoCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarUbigeoCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarUbigeoCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarUbigeoCsv", ReplyAction="http://tempuri.org/IServicio/ListarUbigeoCsvResponse")]
        System.Threading.Tasks.Task<string> ListarUbigeoCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTipoDocumentoCboCsv", ReplyAction="http://tempuri.org/IServicio/ListarTipoDocumentoCboCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarTipoDocumentoCboCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarTipoDocumentoCboCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTipoDocumentoCboCsv", ReplyAction="http://tempuri.org/IServicio/ListarTipoDocumentoCboCsvResponse")]
        System.Threading.Tasks.Task<string> ListarTipoDocumentoCboCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTrabajadorCsv", ReplyAction="http://tempuri.org/IServicio/ListarTrabajadorCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarTrabajadorCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarTrabajadorCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTrabajadorCsv", ReplyAction="http://tempuri.org/IServicio/ListarTrabajadorCsvResponse")]
        System.Threading.Tasks.Task<string> ListarTrabajadorCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerTrabajadorPorIdCsv", ReplyAction="http://tempuri.org/IServicio/ObtenerTrabajadorPorIdCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ObtenerTrabajadorPorIdCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ObtenerTrabajadorPorIdCsv(string idTrabajador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerTrabajadorPorIdCsv", ReplyAction="http://tempuri.org/IServicio/ObtenerTrabajadorPorIdCsvResponse")]
        System.Threading.Tasks.Task<string> ObtenerTrabajadorPorIdCsvAsync(string idTrabajador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerPruebaCovidPorIdCsv", ReplyAction="http://tempuri.org/IServicio/ObtenerPruebaCovidPorIdCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ObtenerPruebaCovidPorIdCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ObtenerPruebaCovidPorIdCsv(string idPruebaCovid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerPruebaCovidPorIdCsv", ReplyAction="http://tempuri.org/IServicio/ObtenerPruebaCovidPorIdCsvResponse")]
        System.Threading.Tasks.Task<string> ObtenerPruebaCovidPorIdCsvAsync(string idPruebaCovid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarPuestoTrabajoCboCsv", ReplyAction="http://tempuri.org/IServicio/ListarPuestoTrabajoCboCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarPuestoTrabajoCboCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarPuestoTrabajoCboCsv(string idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarPuestoTrabajoCboCsv", ReplyAction="http://tempuri.org/IServicio/ListarPuestoTrabajoCboCsvResponse")]
        System.Threading.Tasks.Task<string> ListarPuestoTrabajoCboCsvAsync(string idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarEmpresaCboCsv", ReplyAction="http://tempuri.org/IServicio/ListarEmpresaCboCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarEmpresaCboCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarEmpresaCboCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarEmpresaCboCsv", ReplyAction="http://tempuri.org/IServicio/ListarEmpresaCboCsvResponse")]
        System.Threading.Tasks.Task<string> ListarEmpresaCboCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarEmpresaCsv", ReplyAction="http://tempuri.org/IServicio/ListarEmpresaCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarEmpresaCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarEmpresaCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarEmpresaCsv", ReplyAction="http://tempuri.org/IServicio/ListarEmpresaCsvResponse")]
        System.Threading.Tasks.Task<string> ListarEmpresaCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarEmpresaPorTipoCboCsv", ReplyAction="http://tempuri.org/IServicio/ListarEmpresaPorTipoCboCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarEmpresaPorTipoCboCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarEmpresaPorTipoCboCsv(string idTipoEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarEmpresaPorTipoCboCsv", ReplyAction="http://tempuri.org/IServicio/ListarEmpresaPorTipoCboCsvResponse")]
        System.Threading.Tasks.Task<string> ListarEmpresaPorTipoCboCsvAsync(string idTipoEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTipoEmpresaCboCsv", ReplyAction="http://tempuri.org/IServicio/ListarTipoEmpresaCboCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarTipoEmpresaCboCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarTipoEmpresaCboCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTipoEmpresaCboCsv", ReplyAction="http://tempuri.org/IServicio/ListarTipoEmpresaCboCsvResponse")]
        System.Threading.Tasks.Task<string> ListarTipoEmpresaCboCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarProgresoEmpresaCsv", ReplyAction="http://tempuri.org/IServicio/ListarProgresoEmpresaCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarProgresoEmpresaCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarProgresoEmpresaCsv(string idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarProgresoEmpresaCsv", ReplyAction="http://tempuri.org/IServicio/ListarProgresoEmpresaCsvResponse")]
        System.Threading.Tasks.Task<string> ListarProgresoEmpresaCsvAsync(string idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerEmpresaPorIdCsv", ReplyAction="http://tempuri.org/IServicio/ObtenerEmpresaPorIdCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ObtenerEmpresaPorIdCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ObtenerEmpresaPorIdCsv(string idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerEmpresaPorIdCsv", ReplyAction="http://tempuri.org/IServicio/ObtenerEmpresaPorIdCsvResponse")]
        System.Threading.Tasks.Task<string> ObtenerEmpresaPorIdCsvAsync(string idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerporDniCsv", ReplyAction="http://tempuri.org/IServicio/ObtenerporDniCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ObtenerporDniCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ObtenerporDniCsv(string numeroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerporDniCsv", ReplyAction="http://tempuri.org/IServicio/ObtenerporDniCsvResponse")]
        System.Threading.Tasks.Task<string> ObtenerporDniCsvAsync(string numeroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerIdTrabajadorPorIdUsuarioCsv", ReplyAction="http://tempuri.org/IServicio/ObtenerIdTrabajadorPorIdUsuarioCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ObtenerIdTrabajadorPorIdUsuarioCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ObtenerIdTrabajadorPorIdUsuarioCsv(string idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerIdTrabajadorPorIdUsuarioCsv", ReplyAction="http://tempuri.org/IServicio/ObtenerIdTrabajadorPorIdUsuarioCsvResponse")]
        System.Threading.Tasks.Task<string> ObtenerIdTrabajadorPorIdUsuarioCsvAsync(string idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarProgramacionPruebasCovidCsv", ReplyAction="http://tempuri.org/IServicio/ListarProgramacionPruebasCovidCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarProgramacionPruebasCovidCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarProgramacionPruebasCovidCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarProgramacionPruebasCovidCsv", ReplyAction="http://tempuri.org/IServicio/ListarProgramacionPruebasCovidCsvResponse")]
        System.Threading.Tasks.Task<string> ListarProgramacionPruebasCovidCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarPruebasCovidCsv", ReplyAction="http://tempuri.org/IServicio/ListarPruebasCovidCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarPruebasCovidCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarPruebasCovidCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarPruebasCovidCsv", ReplyAction="http://tempuri.org/IServicio/ListarPruebasCovidCsvResponse")]
        System.Threading.Tasks.Task<string> ListarPruebasCovidCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarResultadoPruebaCboCsv", ReplyAction="http://tempuri.org/IServicio/ListarResultadoPruebaCboCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarResultadoPruebaCboCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarResultadoPruebaCboCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarResultadoPruebaCboCsv", ReplyAction="http://tempuri.org/IServicio/ListarResultadoPruebaCboCsvResponse")]
        System.Threading.Tasks.Task<string> ListarResultadoPruebaCboCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarReporteCovidCsv", ReplyAction="http://tempuri.org/IServicio/ListarReporteCovidCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarReporteCovidCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarReporteCovidCsv(string fechaInicio, string fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarReporteCovidCsv", ReplyAction="http://tempuri.org/IServicio/ListarReporteCovidCsvResponse")]
        System.Threading.Tasks.Task<string> ListarReporteCovidCsvAsync(string fechaInicio, string fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AutorizacionUsuarioCsv", ReplyAction="http://tempuri.org/IServicio/AutorizacionUsuarioCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/AutorizacionUsuarioCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string AutorizacionUsuarioCsv(string idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AutorizacionUsuarioCsv", ReplyAction="http://tempuri.org/IServicio/AutorizacionUsuarioCsvResponse")]
        System.Threading.Tasks.Task<string> AutorizacionUsuarioCsvAsync(string idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarCtrlModulosCboCsv", ReplyAction="http://tempuri.org/IServicio/ListarCtrlModulosCboCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarCtrlModulosCboCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarCtrlModulosCboCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarCtrlModulosCboCsv", ReplyAction="http://tempuri.org/IServicio/ListarCtrlModulosCboCsvResponse")]
        System.Threading.Tasks.Task<string> ListarCtrlModulosCboCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarPruebasCsv", ReplyAction="http://tempuri.org/IServicio/ListarPruebasCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarPruebasCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarPruebasCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarPruebasCsv", ReplyAction="http://tempuri.org/IServicio/ListarPruebasCsvResponse")]
        System.Threading.Tasks.Task<string> ListarPruebasCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTipoEventoCsv", ReplyAction="http://tempuri.org/IServicio/ListarTipoEventoCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarTipoEventoCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarTipoEventoCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTipoEventoCsv", ReplyAction="http://tempuri.org/IServicio/ListarTipoEventoCsvResponse")]
        System.Threading.Tasks.Task<string> ListarTipoEventoCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarCategoriaCsv", ReplyAction="http://tempuri.org/IServicio/ListarCategoriaCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarCategoriaCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarCategoriaCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarCategoriaCsv", ReplyAction="http://tempuri.org/IServicio/ListarCategoriaCsvResponse")]
        System.Threading.Tasks.Task<string> ListarCategoriaCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarBloqueCsv", ReplyAction="http://tempuri.org/IServicio/ListarBloqueCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarBloqueCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarBloqueCsv(string idCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarBloqueCsv", ReplyAction="http://tempuri.org/IServicio/ListarBloqueCsvResponse")]
        System.Threading.Tasks.Task<string> ListarBloqueCsvAsync(string idCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarEspecificacionCsv", ReplyAction="http://tempuri.org/IServicio/ListarEspecificacionCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarEspecificacionCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarEspecificacionCsv(string idCategoria, string idBloque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarEspecificacionCsv", ReplyAction="http://tempuri.org/IServicio/ListarEspecificacionCsvResponse")]
        System.Threading.Tasks.Task<string> ListarEspecificacionCsvAsync(string idCategoria, string idBloque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarZonaCsv", ReplyAction="http://tempuri.org/IServicio/ListarZonaCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarZonaCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarZonaCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarZonaCsv", ReplyAction="http://tempuri.org/IServicio/ListarZonaCsvResponse")]
        System.Threading.Tasks.Task<string> ListarZonaCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarUbicacionCsv", ReplyAction="http://tempuri.org/IServicio/ListarUbicacionCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarUbicacionCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarUbicacionCsv(string idZona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarUbicacionCsv", ReplyAction="http://tempuri.org/IServicio/ListarUbicacionCsvResponse")]
        System.Threading.Tasks.Task<string> ListarUbicacionCsvAsync(string idZona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarBarreraCsv", ReplyAction="http://tempuri.org/IServicio/ListarBarreraCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarBarreraCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarBarreraCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarBarreraCsv", ReplyAction="http://tempuri.org/IServicio/ListarBarreraCsvResponse")]
        System.Threading.Tasks.Task<string> ListarBarreraCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTipoBarreraCsv", ReplyAction="http://tempuri.org/IServicio/ListarTipoBarreraCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarTipoBarreraCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarTipoBarreraCsv(string idBarrera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTipoBarreraCsv", ReplyAction="http://tempuri.org/IServicio/ListarTipoBarreraCsvResponse")]
        System.Threading.Tasks.Task<string> ListarTipoBarreraCsvAsync(string idBarrera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarRangoCumplimientoCsv", ReplyAction="http://tempuri.org/IServicio/ListarRangoCumplimientoCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarRangoCumplimientoCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarRangoCumplimientoCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarRangoCumplimientoCsv", ReplyAction="http://tempuri.org/IServicio/ListarRangoCumplimientoCsvResponse")]
        System.Threading.Tasks.Task<string> ListarRangoCumplimientoCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTipoProgramacionIncidenciaCsv", ReplyAction="http://tempuri.org/IServicio/ListarTipoProgramacionIncidenciaCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarTipoProgramacionIncidenciaCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarTipoProgramacionIncidenciaCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTipoProgramacionIncidenciaCsv", ReplyAction="http://tempuri.org/IServicio/ListarTipoProgramacionIncidenciaCsvResponse")]
        System.Threading.Tasks.Task<string> ListarTipoProgramacionIncidenciaCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarEstadoIncidenciaCsv", ReplyAction="http://tempuri.org/IServicio/ListarEstadoIncidenciaCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarEstadoIncidenciaCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarEstadoIncidenciaCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarEstadoIncidenciaCsv", ReplyAction="http://tempuri.org/IServicio/ListarEstadoIncidenciaCsvResponse")]
        System.Threading.Tasks.Task<string> ListarEstadoIncidenciaCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarIncidenciasActCsv", ReplyAction="http://tempuri.org/IServicio/ListarIncidenciasActCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarIncidenciasActCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarIncidenciasActCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarIncidenciasActCsv", ReplyAction="http://tempuri.org/IServicio/ListarIncidenciasActCsvResponse")]
        System.Threading.Tasks.Task<string> ListarIncidenciasActCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerIncidenciaPorIdCsv", ReplyAction="http://tempuri.org/IServicio/ObtenerIncidenciaPorIdCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ObtenerIncidenciaPorIdCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ObtenerIncidenciaPorIdCsv(string idIncidencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerIncidenciaPorIdCsv", ReplyAction="http://tempuri.org/IServicio/ObtenerIncidenciaPorIdCsvResponse")]
        System.Threading.Tasks.Task<string> ObtenerIncidenciaPorIdCsvAsync(string idIncidencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerIncidenciaPorIdParaSolucionCsv", ReplyAction="http://tempuri.org/IServicio/ObtenerIncidenciaPorIdParaSolucionCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ObtenerIncidenciaPorIdParaSolucionCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ObtenerIncidenciaPorIdParaSolucionCsv(string idIncidencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerIncidenciaPorIdParaSolucionCsv", ReplyAction="http://tempuri.org/IServicio/ObtenerIncidenciaPorIdParaSolucionCsvResponse")]
        System.Threading.Tasks.Task<string> ObtenerIncidenciaPorIdParaSolucionCsvAsync(string idIncidencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerImagenPorIdIncidenciaCsv", ReplyAction="http://tempuri.org/IServicio/ObtenerImagenPorIdIncidenciaCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ObtenerImagenPorIdIncidenciaCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ObtenerImagenPorIdIncidenciaCsv(string idIncidencia, string idTipoImagen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerImagenPorIdIncidenciaCsv", ReplyAction="http://tempuri.org/IServicio/ObtenerImagenPorIdIncidenciaCsvResponse")]
        System.Threading.Tasks.Task<string> ObtenerImagenPorIdIncidenciaCsvAsync(string idIncidencia, string idTipoImagen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarIncidenciaParaSolucionCsv", ReplyAction="http://tempuri.org/IServicio/ListarIncidenciaParaSolucionCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarIncidenciaParaSolucionCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarIncidenciaParaSolucionCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarIncidenciaParaSolucionCsv", ReplyAction="http://tempuri.org/IServicio/ListarIncidenciaParaSolucionCsvResponse")]
        System.Threading.Tasks.Task<string> ListarIncidenciaParaSolucionCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTipoSolucionIncidenciaCsv", ReplyAction="http://tempuri.org/IServicio/ListarTipoSolucionIncidenciaCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarTipoSolucionIncidenciaCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarTipoSolucionIncidenciaCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTipoSolucionIncidenciaCsv", ReplyAction="http://tempuri.org/IServicio/ListarTipoSolucionIncidenciaCsvResponse")]
        System.Threading.Tasks.Task<string> ListarTipoSolucionIncidenciaCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTipoFiltroIncidenciaCsv", ReplyAction="http://tempuri.org/IServicio/ListarTipoFiltroIncidenciaCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ListarTipoFiltroIncidenciaCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ListarTipoFiltroIncidenciaCsv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTipoFiltroIncidenciaCsv", ReplyAction="http://tempuri.org/IServicio/ListarTipoFiltroIncidenciaCsvResponse")]
        System.Threading.Tasks.Task<string> ListarTipoFiltroIncidenciaCsvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerIncidenciaPorFiltroCsv", ReplyAction="http://tempuri.org/IServicio/ObtenerIncidenciaPorFiltroCsvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ObtenerIncidenciaPorFiltroCsvErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ObtenerIncidenciaPorFiltroCsv(string ID_TipoFilto, string Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerIncidenciaPorFiltroCsv", ReplyAction="http://tempuri.org/IServicio/ObtenerIncidenciaPorFiltroCsvResponse")]
        System.Threading.Tasks.Task<string> ObtenerIncidenciaPorFiltroCsvAsync(string ID_TipoFilto, string Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/RegistrarSolucion", ReplyAction="http://tempuri.org/IServicio/RegistrarSolucionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/RegistrarSolucionErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string RegistrarSolucion(Dominio.Solucion oSolucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/RegistrarSolucion", ReplyAction="http://tempuri.org/IServicio/RegistrarSolucionResponse")]
        System.Threading.Tasks.Task<string> RegistrarSolucionAsync(Dominio.Solucion oSolucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ConstruirCorreo", ReplyAction="http://tempuri.org/IServicio/ConstruirCorreoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dominio.Error), Action="http://tempuri.org/IServicio/ConstruirCorreoErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
        string ConstruirCorreo(string idIncidencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ConstruirCorreo", ReplyAction="http://tempuri.org/IServicio/ConstruirCorreoResponse")]
        System.Threading.Tasks.Task<string> ConstruirCorreoAsync(string idIncidencia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChannel : SISFORM_WEB.ServicioWcf.IServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<SISFORM_WEB.ServicioWcf.IServicio>, SISFORM_WEB.ServicioWcf.IServicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Dominio.VistaUsuario AutenticarUsuario(string usuario, string clave) {
            return base.Channel.AutenticarUsuario(usuario, clave);
        }
        
        public System.Threading.Tasks.Task<Dominio.VistaUsuario> AutenticarUsuarioAsync(string usuario, string clave) {
            return base.Channel.AutenticarUsuarioAsync(usuario, clave);
        }
        
        public Dominio.Ubigeo[] ListarUbigeo() {
            return base.Channel.ListarUbigeo();
        }
        
        public System.Threading.Tasks.Task<Dominio.Ubigeo[]> ListarUbigeoAsync() {
            return base.Channel.ListarUbigeoAsync();
        }
        
        public int TrabajadorOperacion(Dominio.Trabajador oTrabajador, string op) {
            return base.Channel.TrabajadorOperacion(oTrabajador, op);
        }
        
        public System.Threading.Tasks.Task<int> TrabajadorOperacionAsync(Dominio.Trabajador oTrabajador, string op) {
            return base.Channel.TrabajadorOperacionAsync(oTrabajador, op);
        }
        
        public Dominio.Trabajador[] ListarTrabajador() {
            return base.Channel.ListarTrabajador();
        }
        
        public System.Threading.Tasks.Task<Dominio.Trabajador[]> ListarTrabajadorAsync() {
            return base.Channel.ListarTrabajadorAsync();
        }
        
        public int EmpresaOperacion(Dominio.Empresa oEmpresa, string op) {
            return base.Channel.EmpresaOperacion(oEmpresa, op);
        }
        
        public System.Threading.Tasks.Task<int> EmpresaOperacionAsync(Dominio.Empresa oEmpresa, string op) {
            return base.Channel.EmpresaOperacionAsync(oEmpresa, op);
        }
        
        public Dominio.Empresa[] ListarEmpresa() {
            return base.Channel.ListarEmpresa();
        }
        
        public System.Threading.Tasks.Task<Dominio.Empresa[]> ListarEmpresaAsync() {
            return base.Channel.ListarEmpresaAsync();
        }
        
        public int ProgresoEmpresaOperacion(Dominio.ProgresoEmpresa oProgresoEmpresa, string op) {
            return base.Channel.ProgresoEmpresaOperacion(oProgresoEmpresa, op);
        }
        
        public System.Threading.Tasks.Task<int> ProgresoEmpresaOperacionAsync(Dominio.ProgresoEmpresa oProgresoEmpresa, string op) {
            return base.Channel.ProgresoEmpresaOperacionAsync(oProgresoEmpresa, op);
        }
        
        public Dominio.ProgresoEmpresa[] ListarProgresoEmpresa(string idEmpresa) {
            return base.Channel.ListarProgresoEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<Dominio.ProgresoEmpresa[]> ListarProgresoEmpresaAsync(string idEmpresa) {
            return base.Channel.ListarProgresoEmpresaAsync(idEmpresa);
        }
        
        public int Criterio1Operacion(Dominio.Criterio1 oCriterio1, string op) {
            return base.Channel.Criterio1Operacion(oCriterio1, op);
        }
        
        public System.Threading.Tasks.Task<int> Criterio1OperacionAsync(Dominio.Criterio1 oCriterio1, string op) {
            return base.Channel.Criterio1OperacionAsync(oCriterio1, op);
        }
        
        public Dominio.Criterio1[] ListarCriterio1(string idEmpresa) {
            return base.Channel.ListarCriterio1(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<Dominio.Criterio1[]> ListarCriterio1Async(string idEmpresa) {
            return base.Channel.ListarCriterio1Async(idEmpresa);
        }
        
        public int Criterio2Operacion(Dominio.Criterio2 oCriterio2, string op) {
            return base.Channel.Criterio2Operacion(oCriterio2, op);
        }
        
        public System.Threading.Tasks.Task<int> Criterio2OperacionAsync(Dominio.Criterio2 oCriterio2, string op) {
            return base.Channel.Criterio2OperacionAsync(oCriterio2, op);
        }
        
        public Dominio.Criterio2[] ListarCriterio2(string idEmpresa) {
            return base.Channel.ListarCriterio2(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<Dominio.Criterio2[]> ListarCriterio2Async(string idEmpresa) {
            return base.Channel.ListarCriterio2Async(idEmpresa);
        }
        
        public int Criterio3Operacion(Dominio.Criterio3 oCriterio3, string op) {
            return base.Channel.Criterio3Operacion(oCriterio3, op);
        }
        
        public System.Threading.Tasks.Task<int> Criterio3OperacionAsync(Dominio.Criterio3 oCriterio3, string op) {
            return base.Channel.Criterio3OperacionAsync(oCriterio3, op);
        }
        
        public Dominio.Criterio3[] ListarCriterio3(string idEmpresa) {
            return base.Channel.ListarCriterio3(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<Dominio.Criterio3[]> ListarCriterio3Async(string idEmpresa) {
            return base.Channel.ListarCriterio3Async(idEmpresa);
        }
        
        public int TrabajadorPuestoOperacion(Dominio.TrabajadorPuesto oTrabajadorPuesto, string op) {
            return base.Channel.TrabajadorPuestoOperacion(oTrabajadorPuesto, op);
        }
        
        public System.Threading.Tasks.Task<int> TrabajadorPuestoOperacionAsync(Dominio.TrabajadorPuesto oTrabajadorPuesto, string op) {
            return base.Channel.TrabajadorPuestoOperacionAsync(oTrabajadorPuesto, op);
        }
        
        public int PruebasCovidOperacion(Dominio.PruebasCovid oPruebasCovid, string op) {
            return base.Channel.PruebasCovidOperacion(oPruebasCovid, op);
        }
        
        public System.Threading.Tasks.Task<int> PruebasCovidOperacionAsync(Dominio.PruebasCovid oPruebasCovid, string op) {
            return base.Channel.PruebasCovidOperacionAsync(oPruebasCovid, op);
        }
        
        public int PruebasCovidMasivo(string data, string idUsuario) {
            return base.Channel.PruebasCovidMasivo(data, idUsuario);
        }
        
        public System.Threading.Tasks.Task<int> PruebasCovidMasivoAsync(string data, string idUsuario) {
            return base.Channel.PruebasCovidMasivoAsync(data, idUsuario);
        }
        
        public int PruebasCovidCarga(Dominio.CargaMasiva[] lstCarga, string idUsuario) {
            return base.Channel.PruebasCovidCarga(lstCarga, idUsuario);
        }
        
        public System.Threading.Tasks.Task<int> PruebasCovidCargaAsync(Dominio.CargaMasiva[] lstCarga, string idUsuario) {
            return base.Channel.PruebasCovidCargaAsync(lstCarga, idUsuario);
        }
        
        public int CtrlAccionOperacion(Dominio.CtrlAccion oCtrlAccion) {
            return base.Channel.CtrlAccionOperacion(oCtrlAccion);
        }
        
        public System.Threading.Tasks.Task<int> CtrlAccionOperacionAsync(Dominio.CtrlAccion oCtrlAccion) {
            return base.Channel.CtrlAccionOperacionAsync(oCtrlAccion);
        }
        
        public int IncidenciaOperacion(Dominio.Incidencia oIncidencia, string op) {
            return base.Channel.IncidenciaOperacion(oIncidencia, op);
        }
        
        public System.Threading.Tasks.Task<int> IncidenciaOperacionAsync(Dominio.Incidencia oIncidencia, string op) {
            return base.Channel.IncidenciaOperacionAsync(oIncidencia, op);
        }
        
        public int IncidenciaImagen(Dominio.Imagen IncidenciaImagen1, string op) {
            return base.Channel.IncidenciaImagen(IncidenciaImagen1, op);
        }
        
        public System.Threading.Tasks.Task<int> IncidenciaImagenAsync(Dominio.Imagen IncidenciaImagen, string op) {
            return base.Channel.IncidenciaImagenAsync(IncidenciaImagen, op);
        }
        
        public string ListarUbigeoCsv() {
            return base.Channel.ListarUbigeoCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarUbigeoCsvAsync() {
            return base.Channel.ListarUbigeoCsvAsync();
        }
        
        public string ListarTipoDocumentoCboCsv() {
            return base.Channel.ListarTipoDocumentoCboCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarTipoDocumentoCboCsvAsync() {
            return base.Channel.ListarTipoDocumentoCboCsvAsync();
        }
        
        public string ListarTrabajadorCsv() {
            return base.Channel.ListarTrabajadorCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarTrabajadorCsvAsync() {
            return base.Channel.ListarTrabajadorCsvAsync();
        }
        
        public string ObtenerTrabajadorPorIdCsv(string idTrabajador) {
            return base.Channel.ObtenerTrabajadorPorIdCsv(idTrabajador);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerTrabajadorPorIdCsvAsync(string idTrabajador) {
            return base.Channel.ObtenerTrabajadorPorIdCsvAsync(idTrabajador);
        }
        
        public string ObtenerPruebaCovidPorIdCsv(string idPruebaCovid) {
            return base.Channel.ObtenerPruebaCovidPorIdCsv(idPruebaCovid);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerPruebaCovidPorIdCsvAsync(string idPruebaCovid) {
            return base.Channel.ObtenerPruebaCovidPorIdCsvAsync(idPruebaCovid);
        }
        
        public string ListarPuestoTrabajoCboCsv(string idEmpresa) {
            return base.Channel.ListarPuestoTrabajoCboCsv(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<string> ListarPuestoTrabajoCboCsvAsync(string idEmpresa) {
            return base.Channel.ListarPuestoTrabajoCboCsvAsync(idEmpresa);
        }
        
        public string ListarEmpresaCboCsv() {
            return base.Channel.ListarEmpresaCboCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarEmpresaCboCsvAsync() {
            return base.Channel.ListarEmpresaCboCsvAsync();
        }
        
        public string ListarEmpresaCsv() {
            return base.Channel.ListarEmpresaCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarEmpresaCsvAsync() {
            return base.Channel.ListarEmpresaCsvAsync();
        }
        
        public string ListarEmpresaPorTipoCboCsv(string idTipoEmpresa) {
            return base.Channel.ListarEmpresaPorTipoCboCsv(idTipoEmpresa);
        }
        
        public System.Threading.Tasks.Task<string> ListarEmpresaPorTipoCboCsvAsync(string idTipoEmpresa) {
            return base.Channel.ListarEmpresaPorTipoCboCsvAsync(idTipoEmpresa);
        }
        
        public string ListarTipoEmpresaCboCsv() {
            return base.Channel.ListarTipoEmpresaCboCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarTipoEmpresaCboCsvAsync() {
            return base.Channel.ListarTipoEmpresaCboCsvAsync();
        }
        
        public string ListarProgresoEmpresaCsv(string idEmpresa) {
            return base.Channel.ListarProgresoEmpresaCsv(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<string> ListarProgresoEmpresaCsvAsync(string idEmpresa) {
            return base.Channel.ListarProgresoEmpresaCsvAsync(idEmpresa);
        }
        
        public string ObtenerEmpresaPorIdCsv(string idEmpresa) {
            return base.Channel.ObtenerEmpresaPorIdCsv(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerEmpresaPorIdCsvAsync(string idEmpresa) {
            return base.Channel.ObtenerEmpresaPorIdCsvAsync(idEmpresa);
        }
        
        public string ObtenerporDniCsv(string numeroDocumento) {
            return base.Channel.ObtenerporDniCsv(numeroDocumento);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerporDniCsvAsync(string numeroDocumento) {
            return base.Channel.ObtenerporDniCsvAsync(numeroDocumento);
        }
        
        public string ObtenerIdTrabajadorPorIdUsuarioCsv(string idUsuario) {
            return base.Channel.ObtenerIdTrabajadorPorIdUsuarioCsv(idUsuario);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerIdTrabajadorPorIdUsuarioCsvAsync(string idUsuario) {
            return base.Channel.ObtenerIdTrabajadorPorIdUsuarioCsvAsync(idUsuario);
        }
        
        public string ListarProgramacionPruebasCovidCsv() {
            return base.Channel.ListarProgramacionPruebasCovidCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarProgramacionPruebasCovidCsvAsync() {
            return base.Channel.ListarProgramacionPruebasCovidCsvAsync();
        }
        
        public string ListarPruebasCovidCsv() {
            return base.Channel.ListarPruebasCovidCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarPruebasCovidCsvAsync() {
            return base.Channel.ListarPruebasCovidCsvAsync();
        }
        
        public string ListarResultadoPruebaCboCsv() {
            return base.Channel.ListarResultadoPruebaCboCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarResultadoPruebaCboCsvAsync() {
            return base.Channel.ListarResultadoPruebaCboCsvAsync();
        }
        
        public string ListarReporteCovidCsv(string fechaInicio, string fechaFin) {
            return base.Channel.ListarReporteCovidCsv(fechaInicio, fechaFin);
        }
        
        public System.Threading.Tasks.Task<string> ListarReporteCovidCsvAsync(string fechaInicio, string fechaFin) {
            return base.Channel.ListarReporteCovidCsvAsync(fechaInicio, fechaFin);
        }
        
        public string AutorizacionUsuarioCsv(string idUsuario) {
            return base.Channel.AutorizacionUsuarioCsv(idUsuario);
        }
        
        public System.Threading.Tasks.Task<string> AutorizacionUsuarioCsvAsync(string idUsuario) {
            return base.Channel.AutorizacionUsuarioCsvAsync(idUsuario);
        }
        
        public string ListarCtrlModulosCboCsv() {
            return base.Channel.ListarCtrlModulosCboCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarCtrlModulosCboCsvAsync() {
            return base.Channel.ListarCtrlModulosCboCsvAsync();
        }
        
        public string ListarPruebasCsv() {
            return base.Channel.ListarPruebasCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarPruebasCsvAsync() {
            return base.Channel.ListarPruebasCsvAsync();
        }
        
        public string ListarTipoEventoCsv() {
            return base.Channel.ListarTipoEventoCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarTipoEventoCsvAsync() {
            return base.Channel.ListarTipoEventoCsvAsync();
        }
        
        public string ListarCategoriaCsv() {
            return base.Channel.ListarCategoriaCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarCategoriaCsvAsync() {
            return base.Channel.ListarCategoriaCsvAsync();
        }
        
        public string ListarBloqueCsv(string idCategoria) {
            return base.Channel.ListarBloqueCsv(idCategoria);
        }
        
        public System.Threading.Tasks.Task<string> ListarBloqueCsvAsync(string idCategoria) {
            return base.Channel.ListarBloqueCsvAsync(idCategoria);
        }
        
        public string ListarEspecificacionCsv(string idCategoria, string idBloque) {
            return base.Channel.ListarEspecificacionCsv(idCategoria, idBloque);
        }
        
        public System.Threading.Tasks.Task<string> ListarEspecificacionCsvAsync(string idCategoria, string idBloque) {
            return base.Channel.ListarEspecificacionCsvAsync(idCategoria, idBloque);
        }
        
        public string ListarZonaCsv() {
            return base.Channel.ListarZonaCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarZonaCsvAsync() {
            return base.Channel.ListarZonaCsvAsync();
        }
        
        public string ListarUbicacionCsv(string idZona) {
            return base.Channel.ListarUbicacionCsv(idZona);
        }
        
        public System.Threading.Tasks.Task<string> ListarUbicacionCsvAsync(string idZona) {
            return base.Channel.ListarUbicacionCsvAsync(idZona);
        }
        
        public string ListarBarreraCsv() {
            return base.Channel.ListarBarreraCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarBarreraCsvAsync() {
            return base.Channel.ListarBarreraCsvAsync();
        }
        
        public string ListarTipoBarreraCsv(string idBarrera) {
            return base.Channel.ListarTipoBarreraCsv(idBarrera);
        }
        
        public System.Threading.Tasks.Task<string> ListarTipoBarreraCsvAsync(string idBarrera) {
            return base.Channel.ListarTipoBarreraCsvAsync(idBarrera);
        }
        
        public string ListarRangoCumplimientoCsv() {
            return base.Channel.ListarRangoCumplimientoCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarRangoCumplimientoCsvAsync() {
            return base.Channel.ListarRangoCumplimientoCsvAsync();
        }
        
        public string ListarTipoProgramacionIncidenciaCsv() {
            return base.Channel.ListarTipoProgramacionIncidenciaCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarTipoProgramacionIncidenciaCsvAsync() {
            return base.Channel.ListarTipoProgramacionIncidenciaCsvAsync();
        }
        
        public string ListarEstadoIncidenciaCsv() {
            return base.Channel.ListarEstadoIncidenciaCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarEstadoIncidenciaCsvAsync() {
            return base.Channel.ListarEstadoIncidenciaCsvAsync();
        }
        
        public string ListarIncidenciasActCsv() {
            return base.Channel.ListarIncidenciasActCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarIncidenciasActCsvAsync() {
            return base.Channel.ListarIncidenciasActCsvAsync();
        }
        
        public string ObtenerIncidenciaPorIdCsv(string idIncidencia) {
            return base.Channel.ObtenerIncidenciaPorIdCsv(idIncidencia);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerIncidenciaPorIdCsvAsync(string idIncidencia) {
            return base.Channel.ObtenerIncidenciaPorIdCsvAsync(idIncidencia);
        }
        
        public string ObtenerIncidenciaPorIdParaSolucionCsv(string idIncidencia) {
            return base.Channel.ObtenerIncidenciaPorIdParaSolucionCsv(idIncidencia);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerIncidenciaPorIdParaSolucionCsvAsync(string idIncidencia) {
            return base.Channel.ObtenerIncidenciaPorIdParaSolucionCsvAsync(idIncidencia);
        }
        
        public string ObtenerImagenPorIdIncidenciaCsv(string idIncidencia, string idTipoImagen) {
            return base.Channel.ObtenerImagenPorIdIncidenciaCsv(idIncidencia, idTipoImagen);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerImagenPorIdIncidenciaCsvAsync(string idIncidencia, string idTipoImagen) {
            return base.Channel.ObtenerImagenPorIdIncidenciaCsvAsync(idIncidencia, idTipoImagen);
        }
        
        public string ListarIncidenciaParaSolucionCsv() {
            return base.Channel.ListarIncidenciaParaSolucionCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarIncidenciaParaSolucionCsvAsync() {
            return base.Channel.ListarIncidenciaParaSolucionCsvAsync();
        }
        
        public string ListarTipoSolucionIncidenciaCsv() {
            return base.Channel.ListarTipoSolucionIncidenciaCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarTipoSolucionIncidenciaCsvAsync() {
            return base.Channel.ListarTipoSolucionIncidenciaCsvAsync();
        }
        
        public string ListarTipoFiltroIncidenciaCsv() {
            return base.Channel.ListarTipoFiltroIncidenciaCsv();
        }
        
        public System.Threading.Tasks.Task<string> ListarTipoFiltroIncidenciaCsvAsync() {
            return base.Channel.ListarTipoFiltroIncidenciaCsvAsync();
        }
        
        public string ObtenerIncidenciaPorFiltroCsv(string ID_TipoFilto, string Filtro) {
            return base.Channel.ObtenerIncidenciaPorFiltroCsv(ID_TipoFilto, Filtro);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerIncidenciaPorFiltroCsvAsync(string ID_TipoFilto, string Filtro) {
            return base.Channel.ObtenerIncidenciaPorFiltroCsvAsync(ID_TipoFilto, Filtro);
        }
        
        public string RegistrarSolucion(Dominio.Solucion oSolucion) {
            return base.Channel.RegistrarSolucion(oSolucion);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarSolucionAsync(Dominio.Solucion oSolucion) {
            return base.Channel.RegistrarSolucionAsync(oSolucion);
        }
        
        public string ConstruirCorreo(string idIncidencia) {
            return base.Channel.ConstruirCorreo(idIncidencia);
        }
        
        public System.Threading.Tasks.Task<string> ConstruirCorreoAsync(string idIncidencia) {
            return base.Channel.ConstruirCorreoAsync(idIncidencia);
        }
    }
}
